### PR TITLE
Refactor out some classes + add test coverage

### PR DESCRIPTION
**Pull request by lsklyut**
I've taken most of the logic that was in Module.php and moved it to classes with some tests. I'm hoping that we can use this as a base to extract a utility for use in other frameworks - I think this concept could benefit Symfony and others just as much as ZF2 (maybe?). I've done a test run on PHP 5.4 (ZF-Skeleton) and confirmed that the cache produced by the master branch is equivalent to the one produced by this pull request. Any further testing + feedback appreciated!

cache-result

### CODE REVIEW

**Comment by lsklyut** [comment]
I've also included included @lvismer 's issue here as part of the PR (Skipping classes with an Annotation tag)

**Comment by snapshotpl** [comment]
I like this changes. What are think @EvanDotPro ?

**Comment by seyfer** [comment]
:+1: it should be merged!

https://github.com/EvanDotPro/EdpSuperluminal/issues/34

**Comment by seyfer** [comment]
Here is a problem..

```
Fatal error: Uncaught exception 'Zend\ServiceManager\Exception\ServiceNotCreatedException' with message 'While attempting to create edpsuperluminalcachebuilder(alias: EdpSuperluminal\CacheBuilder) an invalid factory was registered for this instance type.' 
```

**Pull request closed without merging**
