### PR TITLE
First Pull Request, including type hinting, added dependencies, add lock file

### PR DESCRIPTION
**Pull request by eddiejaoude**

### CODE REVIEW

**Comment by ThaDafinser** [comment]
@eddiejaoude please do not include the lock file. It introduce more problems than it solves...

**Comment by eddiejaoude** [comment]
@ThaDafinser please can you clarify the issues that the lock file causes - or with some resources? Thanks

**Comment by ThaDafinser** [comment]
@eddiejaoude do you have good reasons to include it? (just joking)

I dont have really good ressources for the reason, but maybe this points are good enough?
- supported versions are already defined in composer.json (if a version does not work, or is not tested define it there and make a <= )
- for every new minor or bugfix release you have to update the composer.lock
- doesnt this introduce a lot of composer hand work, if many packages include it? (conflicts)
- I don't know a popular package, which uses the .lock file?
  https://github.com/swiftmailer/swiftmailer
  https://github.com/doctrine/DoctrineORMModule
  https://github.com/Abhoryo/APYDataGridBundle

**Comment by eddiejaoude** [comment]
@ThaDafinser a few good points there. However, I still don't know if it justifies a compelling enough reason for removing it - especially as the lock file is part of the default functionality from composer.

Being @EvanDotPro 's project, I will modify as he requests.

**Comment by ThaDafinser** [comment]
@eddiejaoude i will try to ping Evan per mail again....my PR is currently 3 months old

**Comment by eddiejaoude** [comment]
Ignored. Closing.

**Pull request closed without merging**
